#!/usr/bin/env bash

set -x
source /etc/openhabian.conf

TMPDIR=/tmp
LOG="${storagedir:-/storage}/zram/zramsync.log"
dir="$2"
storeFile="${dir}/zram.tar"

if [[ $# -ne 2 ]]; then echo "$(basename "$0"): wrong usage ! Arguments: sync|recover <dir>" | tee -a "$LOG"; exit 1; fi

if ! [[ -f /etc/ztab ]]; then echo "FAILED (zram not installed)" | tee -a "$LOG"; exit 1; fi

if ! [[ -d $dir ]]; then
	mkdir -p "${dir}"
fi

if [[ $1 == "recover" ]]; then
	mode="recover"
	echo "zramsync recovery starting @ $(date)" | tee -a "$LOG"
	inFile="/etc/ztab"
else
	mode="sync"
	echo "zramsync creating backup @ $(date)" | tee -a "$LOG"
	inFile="${TMPDIR}/zram-device-list"
	rm -f "$storeFile"
fi

while read -r line; do
	case "$line" in
		"#"*)
			# Skip comment line
			continue
			;;

		"")
			# Skip empty line
			continue
			;;

		*)
			set -- $line
			if [[ $1 == "dir" ]] || [[ $1 == "log" ]]; then
				df -k | grep over | tee -a "$LOG"

				OLDWD="$(pwd)"
				if [[ "$mode" = "recover" ]]; then
					cd / || exit 1
					echo "recovering ${5}..." | tee -a "$LOG"
					echo "tar -xvf \"${storeFile}\" \"${5}\"" | tee -a "$LOG"
					tar -xvf "$storeFile" "$5" | tee -a "$LOG"
				else
					PARENTDIR="/opt/zram${2}"
					NEWDIR="${PARENTDIR}/upper"
					ls -ld /opt/zram "$PARENTDIR" "$NEWDIR" | tee -a "$LOG"
					if [[ -d "$NEWDIR" ]]; then
						cd "$NEWDIR" || exit 1
						echo "storing ${3}..." | tee -a "$LOG"
						echo "tar --transform 's,^\.,'$3',' -rvf ${storeFile} ." | tee -a "$LOG"
						tar --transform 's,^\.,'$3',' -rvf "${storeFile}" . | tee -a "$LOG"
					fi
				fi
				cd $OLDWD
			fi
			;;
	esac
done < "$inFile"
